name = "credit-tool"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "credit-tool-db"
database_id = "bbdc2108-d421-49b1-baa6-9325dcae7ef8"
